<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.1 setup script
 * Date: Thu, 15 May 2014 20:58:36 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Aqfeadp1123581321';

/* End of servers configuration */

$cfg['blowfish_secret'] = '53752a1b18ff43.41980290';
$cfg['DefaultLang'] = 'pt_BR';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>